# Matchers
# window class and title is supported
# class match the exact string while title can use a regular expression
# Can use kitty --app-id to avoid relying on title where it might be dynamic
Helix   = /^hx|^helix/
Tmux    = /^tmux/
# https://github.com/zellij-org/zellij/issues/1495
Zellij  = /^[a-z]+-[a-z]+ \| /
Firefox = "firefox"
Foot    = "foot"
Zed     = "dev.zed.Zed"
